apiVersion: v1
kind: ConfigMap
metadata:
  name: dogs-configmap

data:
  config.yaml: |
    port: ":8082"
    postgres:
      host: "dogs-db-service"
      port: 5432
      user: "dogs"
      password: "dogs123"
      db: "dogs_db"